web:
  build: .
  volumes:
    - .:/slicktime
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    - SECRET_KEY_BASE=921114620e49341ab8d1d89bdebeccbd15bd3080483cebafadc9997b08151db5919f1987f90a20bf7dce38a7fff40751405ac105087ddeaef7447bda7f566905

db:
  image: library/postgres:9.3
  ports:
    - "5432:5432"

ember:
  build: ./frontend
  volumes:
    - frontend:/frontend
  ports:
    - "80:80"
    - "31609:31609"
  links:
    - web
